// generate-interfaces.ts - Simple script to generate inject-interfaces.ts

import { writeFile } from 'fs/promises';
import { join } from 'path';

async function generateInjectInterfaces() {
  console.log('Generating interfaces for inject.ts...');
  
  // Generate the content
  let generatedContent = `// inject-interfaces.ts - Generated interfaces for inject.ts
// This file is automatically generated by generate-interfaces.ts
// Do not edit manually - edit types.ts instead

`;

  // Add the StreamingMessageType enum
  generatedContent += `/**
 * Enum for streaming message types shared across components
 */
enum StreamingMessageType {
  STREAMING_STARTED = 'STREAMING_STARTED',
  STREAMING_CHUNK = 'STREAMING_CHUNK',
  STREAMING_COMPLETED = 'STREAMING_COMPLETED'
}

`;

  // Add the base interface
  generatedContent += `interface InjectMessageBase {
  type: StreamingMessageType;
  service: string;
  url: string;
  injectId: string;  // Use injectId for clarity and to avoid ambiguity
  timestamp: number;
  source: 'xhr' | 'fetch';
}
`;

  // Add the StreamingRequestStartedMessage interface
  generatedContent += `interface InjectStreamingRequestStartedMessage extends InjectMessageBase {
  type: StreamingMessageType.STREAMING_STARTED;
  requestBody?: any;
  question: string;  // Renamed from questionContent to question
}
`;

  // Add the StreamingRawDataMessage interface with simplified data object
  generatedContent += `interface InjectStreamingChunkDataMessage extends InjectMessageBase {
    type: StreamingMessageType.STREAMING_CHUNK;
    data: {
      rawChunk: string;
    };
  }
`;

  // Add the StreamingCompletedMessage interface
  generatedContent += `interface InjectStreamingCompletedMessage extends InjectMessageBase {
  type: StreamingMessageType.STREAMING_COMPLETED;
  data: {
    // No additional fields needed as url, injectId, and timestamp are in the base interface
  };
}
`;

  // Write the generated content to the dist folder
  const outputPath = join(process.cwd(), 'dist', 'inject-interfaces.ts');
  await writeFile(outputPath, generatedContent);
  
  console.log('Generated inject-interfaces.ts in dist folder successfully!');
}

// Run the generation
generateInjectInterfaces().catch(console.error);